sudo: required
services:
  - docker

before_install:
  - docker build -t -f rwlee326/docker-react Dockerfile.dev .

script:
  - docker run rwlee326/docker-react npm run test -- --coverage

language: generic
