language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rwlee326/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rwlee326/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-675038381544"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
